### ISSUE TITLE
Showstoppers before public beta

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/taxonomy-editor#348]
### What

```[tasklist]
### Tasks
- [x] Commentaires à préserver dans l’ordre
- [x] Parents dans un ordre non deterministe
- [x] Minimiser le tableau des propriétés (bugs de création et delete)
- [x] Handle xx language
- [x] duplicate id, reading error (what is that?), problèmes de création de liens (parents/enfants)
- [x] language: 400  → remove from editable taxonomies
- [x] countries: 1500 → remove from editable taxonomies
- [x] Noter le commit d’import de la branche et créer la branche depuis ce commit au moment de l’export
- [x] Suppression des stop words lors de la création de node
- [x] Barre de header + Couleur
- [x] Supprimer l’ellipse dans
- [x] Deploy to .org or keep using .net ?
- [ ] “Marketing”: make the UI honest, promote the product, user interview
```

**Comment by alexgarel** [comment]
We can close this it's almost all done.
