### ISSUE TITLE
Fix parsing errors

### ISSUE THREAD

**Issue by eric-nguyen-cs** [openfoodfacts/taxonomy-editor#356]
Duplicate ID, reading errors, child link creation, property order
```[tasklist]
### Tasks
- [ ] https://github.com/openfoodfacts/taxonomy-editor/issues/372
- [x] property order: https://github.com/openfoodfacts/taxonomy-editor/pull/364
- [x] reading error: https://github.com/openfoodfacts/openfoodfacts-server/pull/9730
- [ ] missing child link - better log: https://github.com/openfoodfacts/taxonomy-editor/pull/381
- [ ] missing child links - fix `ingredients.txt` and `origins.txt`
```

**Comment by eric-nguyen-cs** [comment]
To be done after fixing exporting to a PR, as this will facilitate debugging the parsing issues
