### ISSUE TITLE
Taxonomy Editor - Project planning

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/taxonomy-editor#5]
### What

```[tasklist]
### Preparation
    - [ ] Brainstorm on the tech stack of the project
    - [ ] Read documentation for the different related projects in Open Food Facts and understand how taxonomies work in Product Opener
```
```[tasklist]
### Backend
    - [ ] Create a basic backend for Taxonomy Editor with functionality for parsing taxonomies
    - [ ] Implement CRUD of elements within a taxonomy at the backend
```
```[tasklist]
### Frontend
    - [ ] Build a basic UI for CRUD operations on elements
```
```[tasklist]
### Search
    - [ ] Research on different ways of implementing fast search, using algorithms such as Bayer-Moore or other relevant libraries
    - [ ] Some off the shelf solution instead ?
    - [ ] Work on implementing fast search functionality for a component in the backend
    - [ ] Integrate backend fast search implementation with the frontend
  - [ ] Create a backend for parsing taxonomies
  - [ ] Provision for quick search of an component
  - [ ] Implement CRUD of elements in a taxonomy
  - [ ] Research and experiment with different tools for visualization of DAG’s
    - [ ] Alex and Charles’ idea for visualization (Forum post: https://forum.openfoodfacts.org/t/taxonomy-editor-gsoc-2022/90/4)
    - [ ] Focused on one selected component
    - [ ] Visualize ancestors and descendants (only for the selected entry)
    - [ ] Navigation through search 
    - [ ] Options:
      - [ ] react-d3-dag (https://github.com/forivall/react-d3-dag)
      - [ ] XFlow (https://github.com/antvis/XFlow)
  - [ ] Build the basic frontend and backend for displaying the visualization of a taxonomy and its components
  - [ ] Create of dynamic visualization of taxonomies during CRUD operations
  - [ ] Implement a validation process for modifications done on taxonomies
```

```[tasklist]
### Wikidata integration
    - [ ] Get familiar with the Wikidata JSON API
    - [ ] Implement READ operations to add a property from linked Wikidata entity on an existing taxonomy entry
    - [ ] Implement READ operation to create a brand new taxonomy entry from a Wikidata entity
    - [ ] Implement WRITE operation to write the Open Food Facts linked taxonomy entry on a item on Wikidata
```

```[tasklist]
### Add features useful for translators
    - [ ] Add an integration with a translation API to generate translation suggestions
```

```[tasklist]
### Rights and Auth management ?
  - [ ] Rights and Auth management ?
  - [ ] Translators, Editors…
```
```[tasklist]
### Tasks
  - [ ] Test the application and review of test results
  - [ ] Work on the documentation of the project
  - [ ] Review with mentors for any minor changes
  - [ ] Build hierarchy visualizations for taxonomies
  - [ ] Implement validation of a taxonomy modification
```
